name: Package Retail

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*classic*'
    paths-ignore:
      - '.github/**'

env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Run luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: -q

      - name: Package Retail
        uses: BigWigsMods/packager@master
